name: i3blocks-hs-contrib
version: "1.0.0"
synopsis: Base i3blocks written in haskell
license: MIT
author:
  - Christian Panadero <panavtec@gmail.com>
  - Carlos Morera <carlosdelachica@gmail.com>
category: Tools
description: >
  @i3blocks-hs-contrib@ defines a set of blocks for your i3 bar
tested-with:   GHC == 8.4.*
             , GHC == 8.6.*

github: panavtec/i3blocks-hs-contrib

ghc-options: -Wall

dependencies:
  - base >= 4.3 && < 5
  - text < 1.3
  - turtle < 1.6

library:
  source-dirs: src
  exposed-modules:
    - Common

executables:

  AirplaneMode:
    main: Main.hs
    source-dirs:
      - AirplaneMode
      - src

  Bandwidth:
    main: Main.hs
    source-dirs: Bandwidth
    dependencies:
    - time < 1.9
    - transformers < 0.6

  Battery:
    main: Main.hs
    source-dirs:
      - Battery
      - src

  Bitcoin:
    main: Main.hs
    source-dirs: Bitcoin
    dependencies:
    - aeson < 1.5
    - attoparsec < 0.14
    - wreq < 0.5
    - lens < 4.2
    - lens-aeson < 1.1

  Cpu:
    main: Main.hs
    source-dirs:
      - Cpu
      - src

  DateTime:
    main: Main.hs
    source-dirs: DateTime
    dependencies:
    - time < 1.9

  Docker:
    main: Main.hs
    source-dirs:
      - Docker
      - src

  Ip:
    main: Main.hs
    source-dirs: Ip

  Memory:
    main: Main.hs
    source-dirs:
      - Memory
      - src

  OpenVpn:
    main: Main.hs
    source-dirs:
      - OpenVpn
      - src

  Temperature:
    main: Main.hs
    source-dirs: Temperature

  Volume:
    main: Main.hs
    source-dirs:
      - Volume
      - src

  Wifi:
    main: Main.hs
    source-dirs: Wifi
