name: i3blocks-hs-contrib
version: "2.1.0"
synopsis: Base i3blocks written in haskell
license: MIT
author:
  - Christian Panadero <panavtec@gmail.com>
  - Carlos Morera <carlosdelachica@gmail.com>
maintainer:
  - Christian Panadero <panavtec@gmail.com>
  - Carlos Morera <carlosdelachica@gmail.com>
category: Distribution
description: >
  @i3blocks-hs-contrib@ defines a set of blocks for your i3 bar
tested-with:   GHC == 8.4.*
             , GHC == 8.6.*
extra-source-files:
- CHANGELOG.md

github: panavtec/i3blocks-hs-contrib

ghc-options: -Wall

dependencies:
  - base >= 4.3 && < 5
  - text < 2
  - turtle < 2

library:
  source-dirs: src
  exposed-modules:
    - Common

executables:

  AirplaneMode:
    main: Main.hs
    source-dirs:
      - AirplaneMode
      - src

  Bandwidth:
    main: Main.hs
    source-dirs: Bandwidth
    dependencies:
    - time < 2
    - transformers < 2

  Battery:
    main: Main.hs
    source-dirs:
      - Battery
      - src

  Bitcoin:
    main: Main.hs
    source-dirs: Bitcoin
    dependencies:
    - aeson < 2
    - attoparsec < 1
    - http-client < 1
    - http-client-tls < 1

  Cpu:
    main: Main.hs
    source-dirs:
      - Cpu
      - src

  DateTime:
    main: Main.hs
    source-dirs: DateTime
    dependencies:
    - time < 2

  Docker:
    main: Main.hs
    source-dirs:
      - Docker
      - src

  Ip:
    main: Main.hs
    source-dirs: Ip

  Memory:
    main: Main.hs
    source-dirs:
      - Memory
      - src

  OpenVpn:
    main: Main.hs
    source-dirs:
      - OpenVpn
      - src

  Temperature:
    main: Main.hs
    source-dirs: Temperature

  Volume:
    main: Main.hs
    source-dirs:
      - Volume
      - src

  Wifi:
    main: Main.hs
    source-dirs: Wifi
